name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyarmor pyinstaller

    - name: Obfuscate code with PyArmor
      run: |
        pyarmor gen --src=./ --entry=phantomnet-client.py obf_dist

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile obf_dist/phantomnet-client.py

    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: phantomnet-client-windows-exe
        path: dist/phantomnet-client.exe
